name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify deploy
        run: curl -s -X POST "https://api.netlify.com/build_hooks/6a9a7df93f91b39aa73336d4"
